### ISSUE TITLE
Non-string `caller-line` cannot be parsed

### ISSUE THREAD

**Issue by gcq** [pamburus/hl#106]
```
$ echo '{"filename": "whtvr", "lineno": 1}' | hl -P
        ---         |(?)| @ whtvr:

$ echo '{"filename": "whtvr", "lineno": "1"}' | hl -P
        ---         |(?)| @ whtvr:1
```

I tried making a PR but had to change the second type of `FileLine` to `String`, which doesn't look like it's the best way. First time diving into a rust codebase.

**Comment by pamburus** [comment]
Thanks for reporting the issue.
Yes, I think both integer and string values should be supported here.
I'll make a fix.
