### ISSUE TITLE
Handle log level in kubernetes logs

### ISSUE THREAD

**Issue by msvticket** [pamburus/hl#156]
Thank you for #154 , which improved parsing of kubernetes json logs: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format

The remaining thing that would be nice to have addressed is level. As you can see above it is handled a bit differently. 

## Info

The presence of the field v means info. But a higher number is reasonable to interpret as debug.

So a variant for the level configuration could look like:

        - names: [v]
          values:
            debug: [2, 3, 4]
            info: [0,1]

Except that it doesn't work. Going back to the example I gave in #153:

`{"ts":1710923450736.8257,"caller":"eligibility/eligibility.go:104","msg":"Scale-down calculation: ignoring 2 nodes unremovable in the last 5m0s\n","v":1}`

For this with the configuration above hl still show `(?)` as level. But if I put the value of v in quotes, making it a string, it does work. I.e. with  this example hl shows the log level as info:

`{"ts":1710923450736.8257,"caller":"eligibility/eligibility.go:104","msg":"Scale-down calculation: ignoring 2 nodes unremovable in the last 5m0s\n","v":"1"}`

So I propose support for converting field value and values in the configuration to a common type before comparison.

## Error

An error in these logs is signified by the presence of the field `err`, the content of which you would also like to see. As far as I can see this is not possible to configure at the moment. So I propose a new feature to make the presence of a field indicate a level. Maybe the configuration could look like this:

        - names: [err]
          values:
            error: exists

**Comment by pamburus** [comment]
Implemented, please check [v0.27.0-beta.4](https://github.com/pamburus/hl/releases/tag/v0.27.0-beta.4)

**Comment by msvticket** [comment]
Thanks, now it works well for k8s logs!
