### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by YossiCohen** [pamburus/hl#455]
Hi,

I have this JSON log:
`[
  {
    "module": "Settings",
    "logMessage": "New settings saved",
    "timestamp": 1727204366872,
    "level": 4,
    "payload": {
      "logLevel": "5",
    },
    "id": 3125,
    "timeString": "24 Sep 2024 21:59:26"
  },
  {
    "module": "MainHelper",
    "logMessage": "getInfo",
    "timestamp": 1727204373575,
    "level": 5,
    "payload": [
      [
        "URL",
        "https://www.bing.com"
      ],
      [
        "User",
        "foo"
      ]
    ],
    "id": 3126,
    "timeString": "24 Sep 2024 21:59:33"
  },
  {
    "module": "BOO",
    "logMessage": "no message",
    "timestamp": 1727204373585,
    "level": 4,
    "payload": {},
    "id": 3127,
    "timeString": "24 Sep 2024 21:59:33"
  }
 ]`

and when I try to filter it with this command:
`hl 1.json -f module=Settings`
I get no output.
Can you please assist?

**Comment by pamburus** [comment]
Hi,

JSON log should be in a [jsonl](https://jsonlines.org) format with one JSON object per line.
The example above looks like an array of objects. 
It is also not valid JSON. It has a trailing comma here: `{ "logLevel": "5", }`.
If you fix the trailing comma, you can convert it to a JSON log format using the [jq](https://jqlang.github.io/jq/) tool like this:
```bash
$ <1.json jq -c '.[]' | hl -f module=Settings
2024-09-24 18:59:26.872 UTC │(?)│ module=Settings logMessage="New settings saved" level=4 payload.logLevel="5" id=3125 timeString="24 Sep 2024 21:59:26"
```

A custom configuration is needed for this type of log to handle the `level` and `logMessage` correctly. For instructions on creating a custom configuration file, see the [Configuration Files](https://github.com/pamburus/hl?tab=readme-ov-file#configuration-files) section in the README.md file. You can start with the default [config.yaml](https://github.com/pamburus/hl/blob/master/etc/defaults/config.yaml#L30-L46) file. You can also remove any elements you don't want to customize and let the defaults take over.

Could you please share what software produces these log messages, in case it is something well-known?

**Comment by pamburus** [comment]
By the way, if you want to fix trailing commas automatically, you can use [fx](https://github.com/antonmedv/fx) tool together  with [jq](https://jqlang.github.io/jq/) for the mentioned format like this:
```bash
<1.json fx . | jq -c '.[]' | hl
```

**Comment by YossiCohen** [comment]
Hi,

I'll try your suggestions (the comma after the logLevel is my mistake because I've manually cleaned some clutter in the example)
The log is an output of a tool I work with, it's an array of object that is parsed to JSON and exported to file.

Thanks Pavel for your prompt response.
