### ISSUE TITLE
When input files is wildcard (*) in windows11, it treat as filename

### ISSUE THREAD

**Issue by sovernut** [pamburus/hl#597]
Hi pamburus

I got some error while try command
`hl *.txt` 
and error message is
```
error: failed to get information on file '*.txt': The filename, directory name, or volume label syntax is incorrect. (os error 123)
```
or am i running wrong command ? 
```
OS: Windows11
Shell: Powershell
```

Thanks for great tools 😍

**Comment by pamburus** [comment]
It looks like wildcard expansion does not work on Windows.
Thanks for reporting, I will fix it soon.
