### ISSUE TITLE
Add ability to set custom fields (time/level)

### ISSUE THREAD

**Issue by xxxcoltxxx** [pamburus/hl#8]
Some programs writes logs with custom field names. In my case, `datetime` field instead of `time` and `level_name` instead of `level`:

```
{"datetime":"2021-05-21T02:53:11+03:00","level_name":"info","message":"Rabbitmq connection created"}
```

And the `hl` output:
```
        ---         |(?)| Rabbitmq connection created datetime='2021-05-21T02:53:11+03:00' level-name='info'
```

**Comment by pamburus** [comment]
Thank you for reporting the issue.
I think we can't go further with command-line arguments only.
Configuration file support is needed for such advanced options.
I started working on this, but due to lack of time, things can go slowly.
