### ISSUE TITLE
add "not containing sub-string"

### ISSUE THREAD

**Issue by k2s** [pamburus/hl#92]
There is `hl example.log -f component=tsdb` and its negation `hl example.log -f component!=tsdb`.

Then there is `hl example.log -f provider~=string`, but its negation doesn't work `hl example.log -f provider!~=string`.

Thank you.

**Comment by pamburus** [comment]
It actually works, but you probably expected it to work in a different way.
`hl example.log -f provider!~=string` shows all messages that _have_ the `provider` field _and_ its value _does not contain_ `string`.
This behavior is quite common for filtering by fields, and it is usually convenient. But it does not work as an exact negation, which can be confusing.
Do you really need a way to show all messages that _do not have_ this field or whose value _does not contain_ the specified substring?

**Comment by k2s** [comment]
Thank you. The problem was missing single quote.

This works perfectly for me:

`hl log.log -h pid -h name -h hostname -h module -f 'msg!~=Unhandled' -l warn`
